version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker
      dockerfile: ./php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/
    networks:
      - santa

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:rw
      - ./docker/php-fpm/php.ini:/etc/php/8.1/cli/php.ini
    depends_on:
      - php-fpm
    networks:
        - santa

  mailer:
    image: maildev/maildev
    container_name: ${COMPOSE_PROJECT_NAME}_mailer
    ports:
      - 1025
      - 1080
    networks:
      - santa

  database:
    image: 'postgres:alpine'
    container_name: ${COMPOSE_PROJECT_NAME}_database
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "main"
      POSTGRES_USER: "main"
      POSTGRES_DB: "main"
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '54320'
    networks:
      - santa

networks:
  santa:
    driver: bridge

volumes:
  database: